services:
  robin:
    build: ./bots/robin
    container_name: robin
    env_file:
      - ./bots/robin/.env
    volumes:
      - ./bots/robin:/app
    working_dir: /app
    command: python ollama_discord_bot.py

  nami:
    build: ./bots/nami
    container_name: nami
    env_file:
      - ./bots/nami/.env
    volumes:
      - ./bots/nami:/app
    working_dir: /app
    command: python nami_bot.py